projects:
  eclient:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: 4slnrttulvfj5jkfgok6ufz2si
      endpoints:
        prod: >-
          https://jvad45zlcnhlnn54b37qh4cknm.appsync-api.us-east-1.amazonaws.com/graphql
